# Generated by Django 3.2.6 on 2021-08-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_HUNDRED', models.IntegerField(default=0, null=True)),
                ('D_FIFTY', models.IntegerField(default=0, null=True)),
                ('D_TWENTY', models.IntegerField(default=0, null=True)),
                ('D_TEN', models.IntegerField(default=0, null=True)),
                ('C_FIFTY', models.IntegerField(default=0, null=True)),
                ('C_TWENTY', models.IntegerField(default=0, null=True)),
                ('C_TEN', models.IntegerField(default=0, null=True)),
                ('C_FIVE', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
